FROM debian:latest

RUN apt-get update && apt-get install -y openssh-server curl rsyslog git sudo

# Configure SSH
RUN mkdir /var/run/sshd
RUN useradd -m -d /home/admin admin
RUN useradd -m -d /home/admlukas admlukas && usermod -aG sudo admlukas


WORKDIR /home/admlukas
RUN mkdir .ssh
RUN chmod 700 .ssh
RUN touch .ssh/authorized_keys
RUN chmod 600 .ssh/authorized_keys
RUN curl https://github.com/declercklouis.keys > /home/admlukas/.ssh/authorized_keys


## don't allow password login for ssh admlukas
RUN echo 'admlukas:12OKQ8jqsd9!qsd' | chpasswd

#password for user login
RUN echo 'root:redhat' | chpasswd
RUN echo 'admin:admin' | chpasswd

#password for user login
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# create scripts dir and copy scripts
RUN mkdir /tmp/scripts
WORKDIR /tmp/scripts
COPY ./files/ssh-container/scripts .
CMD ["/bin/bash", "/tmp/scripts/start.sh"]

EXPOSE 22
